security:
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_CONNECT_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        SensioLabs\JobBoardBundle\Entity\User: plaintext

    providers:
        sensiolabs_connect:
            id: sensiolabs_jobboard.security.userprovider
#            connect_memory:
#                users:
#                    36221b12-f362-4dca-8724-4da82ef2ba49: "ROLE_ADMIN" # Sarah Khalil
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            sensiolabs_connect:
                check_path:  /session/callback
                login_path:  /login
                remember_me: false
                provider:    sensiolabs_connect
            logout:          ~
            anonymous:       true

    access_control:
        - { path: ^/manage, roles: ROLE_USER }
        - { path: ^/[\w\-]+/[\w\-]+/[\w\-]+/(update|pay)$, roles: ROLE_USER }
