security:
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_CONNECT_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        SensioLabs\JobBoardBundle\Entity\User: plaintext

    providers:
        sensiolabs_connect:
            id: sensiolabs_jobboard.security.userprovider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern:    ^/api
            anonymous:  true

        secured_area:
            pattern:    ^/
            sensiolabs_connect:
                check_path:  /session/callback
                login_path:  /login
                remember_me: false
                provider:    sensiolabs_connect
            logout:          ~
            anonymous:       true

    access_control:
        - { path: ^/api, roles: API_ACCESS }
        - { path: ^/manage, roles: ROLE_CONNECT_USER }
        - { path: ^/backend, roles: ROLE_ADMIN }
        - { path: ^/[\w\-]+/[\w\-]+/[\w\-]+/(update|pay)$, roles: ROLE_USER }
